import torch
from huggingface_hub import hf_hub_download
from torch import nn
from torchvision.utils import save_image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import json
import base64
import os


class Generator(nn.Module):
    def __init__(self, nc=4, nz=100, ngf=64):
        super(Generator, self).__init__()
        self.network = nn.Sequential(
            nn.ConvTranspose2d(nz, ngf * 4, 3, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 4, ngf * 2, 3, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 2, ngf, 4, 2, 0, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf, nc, 4, 2, 1, bias=False),
            nn.Tanh(),
        )

    def forward(self, input):
        output = self.network(input)
        return output


model = Generator()
weights_path = hf_hub_download('nateraw/cryptopunks-gan', 'generator.pth')
model.load_state_dict(torch.load(weights_path, map_location=torch.device('cpu')))
model.eval()

print("Generando punks.png...")
out = model(torch.randn(64, 100, 1, 1))
save_image(out, "punks.png", normalize=True)
print("Generated punks.png with 64 punks!")

img = mpimg.imread("punks.png")
plt.imshow(img)
plt.axis("off")
plt.title("Generated CryptoPunks")
plt.show()

print("Generando lotes para la pagina web...")
NUM_BATCHES = 20
batches = {}

for i in range(NUM_BATCHES):
    noise = torch.randn(64, 100, 1, 1)
    with torch.no_grad():
        output = model(noise)

    filename = f"punks_{i}.png"
    save_image(output, filename, normalize=True)

    with open(filename, "rb") as f:
        img_data = base64.b64encode(f.read()).decode("ascii")

    batches[f"batch_{i}"] = img_data
    print(f"  Lote {i+1}/{NUM_BATCHES} generado")

    os.remove(filename)

js_content = "// CryptoPunks GAN - Pre-generated batches\n"
js_content += "// Generated by generate_punks.py using the real GAN model\n"
js_content += "// Each batch contains 64 punks as base64 PNG images\n\n"
js_content += "const PUNKS_DATA = " + json.dumps(batches) + ";\n"
js_content += "const PUNKS_TOTAL_BATCHES = " + str(NUM_BATCHES) + ";\n"

with open("punks_data.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"\nHecho! Se creo punks_data.js con {NUM_BATCHES} lotes ({NUM_BATCHES * 64} punks)")
print("Sube index.html, styles.css, script.js y punks_data.js a Vercel")